network.host: 0.0.0.0
cluster.name: "elkcluster"

discovery.type: single-node
node.name: ${node.name}
xpack.security.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: certs/master-node/master-node.key
xpack.security.http.ssl.certificate: certs/master-node/master-node.crt
xpack.security.http.ssl.certificate_authorities: certs/ca/ca.crt
xpack.security.http.ssl.verification_mode: certificate
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.key: certs/master-node/master-node.key
xpack.security.transport.ssl.certificate: certs/master-node/master-node.crt
xpack.security.transport.ssl.certificate_authorities: certs/ca/ca.crt
xpack.security.transport.ssl.verification_mode: certificate
