- module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts: ["http://master-node:9200"] 
    #scope: node 
    username: "elastic"
    password: "testing"
    ssl:
      enabled: true
      certificate_authorities: "/home/elasticsearch/elasticsearch-8.3.1/config/certs/ca/ca.crt"
      verification_mode: "certificate"
