metricbeat.config.modules:
  path: ./modules.d/*.yml

output.elasticsearch:
  hosts: ["master-node:9200"]
  username: "elastic"
  password: "testing"
  protocol: "https"
  ssl:
    enabled: true
    certificate_authorities: "/home/elasticsearch/elasticsearch-8.3.1/config/certs/ca/ca.crt"


setup.kibana:
    host: "kibana:5601"
    protocol: "http"
    username: "elastic"
    password: "testing"
