version: "2.2"

services:
  master-node:
    build: ./src/elastic_stack/elasticsearch/.
    image: elasticsearch37
    volumes:
      - certs:/home/elasticsearch/elasticsearch-8.3.1/config/certs
      - master-node-data:/home/elasticsearch/elasticsearch-8.3.1/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ELASTIC_USER_HASH=${ELASTIC_USER_HASH}
      - node.name=master-node
      - cluster.name=elkcluster
      - cluster.initial_master_nodes=master-node,second-node
      - discovery.seed_hosts=second-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    mem_limit: 3073741824
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/ca/ca.crt ]"]
      interval: 50s
      timeout: 50s
      retries: 1200
  second-node:
    depends_on:
      master-node:
        condition: service_healthy
    image: elasticsearch37
    volumes:
      - certs:/home/elasticsearch/elasticsearch-8.3.1/config/certs
      - second-node-data:/home/elasticsearch/elasticsearch-8.3.1/data
    ports:
      - 39200:9200
    environment:
      - ELASTIC_USER_HASH=${ELASTIC_USER_HASH}
      - node.name=second-node
      - cluster.name=elkcluster
      - cluster.initial_master_nodes=master-node,second-node
      - discovery.seed_hosts=master-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    mem_limit: 3073741824
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/ca/ca.crt ] && curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'"]
      interval: 10s
      timeout: 10s
      retries: 1200
  kibana:
    volumes:
      - certs:/etc/kibana/config/certs
    depends_on:
      second-node:
        condition: service_healthy
    build: ./src/elastic_stack/kibana/.
    image: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    mem_limit: 3073741824
  logstash:
    build: ./src/elastic_stack/logstash/.
    image: logstash
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - 9600:9600
    volumes:
      - certs:/root/config/certs
    depends_on:
      - kibana
  elastic-agent:
    image: docker.elastic.co/beats/elastic-agent:8.3.1
    container_name: elastic-agent
    volumes:
      - certs:/root
    user: root
    environment:
      - FLEET_SERVER_ELASTICSEARCH_CA=/root/ca/ca.crt
      - FLEET_SERVER_ENABLE=true
      - FLEET_SERVER_ELASTICSEARCH_HOST=https://master-node:9200
      - FLEET_SERVER_ELASTICSEARCH_USERNAME=elastic
      - FLEET_SERVER_ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_FLEET_SETUP=1
      - KIBANA_HOST=http://kibana:5601
      - KIBANA_USERNAME=elastic
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
      - FLEET_SERVER_ELASTICSEARCH_INSECURE=true
      - FLEET_SERVER_POLICY=fleet-server-policy
    depends_on:
      - metricbeat
  metricbeat:
    build: ./src/elastic_stack/metricbeat/.
    image: metricbeat
    volumes:
      - certs:/root/config/certs
    depends_on:
      - kibana
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
volumes:
  certs:
    driver: local
  master-node-data:
    driver: local
  second-node-data:
    driver: local
