version: "2.2"

services:
  master-node:
    build: ./src/elastic_stack/elasticsearch/.
    image: elasticsearch37
    volumes:
      - certs:/home/elasticsearch/elasticsearch-8.3.1/config/certs
      - master-node-data:/home/elasticsearch/elasticsearch-8.3.1/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=master-node
      - cluster.name=elkcluster
      - cluster.initial_master_nodes=master-node,second-node
      - discovery.seed_hosts=second-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    mem_limit: 1073741824
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/ca/ca.crt ]"]
      interval: 50s
      timeout: 50s
      retries: 1200
  second-node:
    depends_on:
      master-node:
        condition: service_healthy
    image: elasticsearch37
    volumes:
      - certs:/home/elasticsearch/elasticsearch-8.3.1/config/certs
      - second-node-data:/home/elasticsearch/elasticsearch-8.3.1/data
    environment:
      - node.name=second-node
      - cluster.name=elkcluster
      - cluster.initial_master_nodes=master-node,second-node
      - discovery.seed_hosts=master-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    mem_limit: 1073741824
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/ca/ca.crt ] && curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'"]
      interval: 10s
      timeout: 10s
      retries: 120
volumes:
  certs:
    driver: local
  master-node-data:
    driver: local
  second-node-data:
    driver: local
