metricbeat.config.modules:
  path: ./modules.d/*.yml
  reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["https://master-node:9200"]
  username: "elastic"
  password: '${ELASTIC_PASSWORD}'
  ssl:
    enabled: true
    certificate_authorities: "/root/config/certs/ca/ca.crt"

# enabled modules for monitoring
metricbeat.modules:
- module: elasticsearch
  xpack.enabled: true
  period: 10s
  scope: cluster
  hosts: ["https://master-node:9200"]
  username: "elastic"
  password: '${ELASTIC_PASSWORD}'
  ssl:
    enabled: true
    certificate_authorities: "/root/config/certs/ca/ca.crt"
- module: kibana
  metricsets: ["status"]
  period: 10s
  xpack.enabled: true
  hosts: ["http://kibana:5601"]
  username: "elastic"
  password: '${ELASTIC_PASSWORD}'
- module: logstash
  metricsets: ["node", "node_stats"]
  period: 10s
  hosts: ["localhost:9600"]
  username: "elastic"
  password: '${ELASTIC_PASSWORD}'
  xpack.enabled: true

setup.kibana:
    host: "kibana:5601"
    protocol: "http"
    username: "elastic"
    password: '${ELASTIC_PASSWORD}'

